kind = "api"
previewPath = "/"
title = "SLC Auto Shop"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 3000
name = "SLC Auto Shop"
paths = ["/"]

[services.development]
run = "node server.js"

[services.production]
run = "node artifacts/slcautoshop/server.js"
